services:
  queue_backend:
    container_name: queue_bckend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
       - ./backend:/app
    environment:
      DB_NAME: 'queue_monitor'
      DB_USER: 'sagarika'
      DB_PASSWORD: 'Sagarika@%71'
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - my_network

  queue_frontend:
    container_name: queue_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
       - ./frontend:/app
    restart: unless-stopped
    networks:
      - my_network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    volumes: 
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'Sagarika@%71'
      MYSQL_PASSWORD: 'Sagarika@%71'
      MYSQL_USER: 'sagarika'
      MYSQL_HOST: 'localhost'
    ports:
       - '3307:3306'
    restart: unless-stopped
    healthcheck:
      test: ["CMD","ping","-h","localhost","-u","sagarika","-pSagarika@%71"]
      interval: 20s
      timeout: 20s
      retries: 20
    networks:
      - my_network

volumes:
  mysql-data:

networks:
  my_network:
    driver: bridge


    

    